### ISSUE TITLE
segfault on teststand

### ISSUE THREAD

**Issue by tlatorre-uchicago** [snoplus/penn_daq2#10]
I get a segfault when running the following command on the teststand: `crate_init -c 19 -s 100 -x`. The segfault occurs just after `Now sending database to XL3`.

**Comment by tannerbk** [comment]
Were you running an up to date version with the current master?

Its almost certainly this line: 
https://github.com/snoplus/penn_daq2/blob/master/src/xl3/XL3Cmds.cpp#L402

Which is commented out in the branch that is typically run on penn_daq_original. I'll submit a fix for this.

**Comment by tannerbk** [comment]
I think once this is merged: https://github.com/mastbaum/debugdb/pull/82 
it should fix this.

**Comment by tannerbk** [comment]
This should be fixed now, I tested it on the teststand.
